# -*- coding: utf-8 -*-
"""Copy of toxic comment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3zFQBqJXKYTp5dHTfIqzRH1rm3UPhu3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/comments toxicity.csv", encoding='latin1')

df.info()

df.describe()

df.shape

df.isnull().sum()

df.drop_duplicates(subset=['comment_text'], inplace=True)
display(f'shape after dropping duplicates: {df.shape}')

df.dropna(subset=['comment_text'], inplace=True)

df['comment_text'] = df['comment_text'].str.lower()

df['comment_text'] = df['comment_text'].str.strip()

df['comment_text'] = df['comment_text'].str.replace(r'http\S+|www. \S+', '',regex=True)

df = df[df['comment_text'] != '']

"""**TOKENIZATION**"""

import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

import nltk
nltk.download('punkt_tab')
df['tokens'] = df['comment_text'].apply(word_tokenize)

df[['comment_text','tokens']].head(2)

"""**STOP WORD REMOVAL**"""

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(lambda x: [word for word in x if word not in stop_words])

"""**Lemmatization**"""

import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

df['tokens'] = df['tokens'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])

"""**Convert text into numbers**"""

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=5000)
df['comment_text'] = df['comment_text'].fillna('')
X = tfidf.fit_transform(df['comment_text'])
print("Shape:", X.shape)

toxicity_map = {'non-toxic': 0, 'toxic': 1}
df['label_toxicity'] = df['toxic']

from sklearn.model_selection import train_test_split
y = df['label_toxicity']
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""**Logistic Regression**"""

from sklearn.linear_model import LogisticRegression
log_reg_model = LogisticRegression(max_iter=1000)
log_reg_model.fit(x_train, y_train)
print("Logistic Regression model trained successfully")

y_predict = log_reg_model.predict(x_test)

sample = ["you are a good boy "]
sample = tfidf.transform(sample)
print(log_reg_model.predict(sample))

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
print("Accuracy:", accuracy_score(y_test, y_predict))
print("precision:", precision_score(y_test, y_predict))
print("recall:", recall_score(y_test, y_predict))
print("f1 Score:", f1_score(y_test, y_predict))
print("confusion matrix:\n", confusion_matrix(y_test, y_predict))
print("classification report:\n", classification_report(y_test, y_predict))